### ISSUE TITLE
Create detailed favorite stop map view

### ISSUE THREAD

**Issue by leopiney** [leopiney/light-stm-rn#6]
* [x] Open complete map view with stop marker and all buses updating in real time
* [x] Make positions update every 15 seconds
* [ ] Tilt map towards direction of the buses
